name: Build and Test .NET Project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Smoke Test Only
      run: dotnet test --no-build --filter TestCategory=Smoke --verbosity normal

    - name: Run Unit Tests Only
      run: dotnet test --no-build --filter TestCategory=Unit --verbosity normal

    - name: Run Integration Tests Only
      run: dotnet test --no-build --filter TestCategory=Integration --verbosity normal
